name: Convert PDF to PNG and Crop

on:
  push:
    paths:
      - '**/Export.pdf'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Find directory of Export.pdf
        id: find_dir
        run: |
          # Trouver tous les fichiers Export.pdf modifiés dans le push
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'Export.pdf' || true)
          if [ -z "$files" ]; then
            # fallback: chercher dans tout le repo
            files=$(find . -name Export.pdf)
          fi
          echo "Export.pdf found at: $files"
          # Prendre le premier (en cas de plusieurs)
          first_file=$(echo "$files" | head -n1)
          dir=$(dirname "$first_file")
          echo "DIR=$dir"
          echo "dir=$dir" >> "$GITHUB_OUTPUT"

      - name: Install Poppler & ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils imagemagick

      - name: Convert PDF to PNG
        run: |
          DIR="${{ steps.find_dir.outputs.dir }}"
          echo "Working in dir: $DIR"
          rm -f "$DIR"/*.png
          mkdir -p "$DIR"
          pdftoppm -png "$DIR"/Export.pdf "$DIR"/Export

      - name: Trim white borders from PNGs (Above and Below only)
        run: |
          DIR="${{ steps.find_dir.outputs.dir }}"
          for img in "$DIR"/*.png; do
            echo "🔧 Processing $img"
            convert "$img" -gravity South -splice 0x1 "$img"
            width=$(identify -format "%w" "$img")
            height=$(identify -format "%h" "$img")
            y=$((height - 1))
            convert "$img" -fill black -draw "rectangle 0,$y $((width - 1)),$y" "$img"
            convert "$img" -trim +repage "$img"
            mogrify -gravity South -chop 0x1 "$img"
            convert "$img" -gravity North -splice 0x1 "$img"
            width=$(identify -format "%w" "$img")
            convert "$img" -fill black -draw "rectangle 0,0 $((width - 1)),0" "$img"
            convert "$img" -trim +repage "$img"
            mogrify -gravity North -chop 0x1 "$img"
            echo "✅ Done: $img"
          done

      - name: Combine all PNGs into one image
        run: |
          DIR="${{ steps.find_dir.outputs.dir }}"
          convert "$DIR"/*.png -append "$DIR"/Export-Full.png

      - name: Trim white borders from final image
        run: |
          DIR="${{ steps.find_dir.outputs.dir }}"
          convert "$DIR"/Export-Full.png -trim +repage "$DIR"/Export-Full.png

      - name: Commit PNGs to repo
        run: |
          DIR="${{ steps.find_dir.outputs.dir }}"
          git config user.name github-actions
          git config user.email actions@github.com
          git add "$DIR"/*.png
          git commit -m "Auto-convert and crop PDF pages" || echo "ℹ️ Aucun changement PNG à commit"
          git push

      - name: Ensure index.html exists and commit if needed
        run: |
          DIR="${{ steps.find_dir.outputs.dir }}"
          PARENT_DIR=$(dirname "$DIR")
          GRANDPARENT_DIR=$(dirname "$PARENT_DIR")

          echo "🔍 Vérification de $PARENT_DIR/index.html ..."
          if [ ! -f "$PARENT_DIR/index.html" ]; then
            echo "📄 index.html manquant. Copie depuis $GRANDPARENT_DIR/index-exemple.html ..."
            cp "$GRANDPARENT_DIR/index-exemple.html" "$PARENT_DIR/index.html"
            
            git config user.name github-actions
            git config user.email actions@github.com
            git add "$PARENT_DIR/index.html"
            git commit -m "Ajout automatique de index.html manquant" || echo "ℹ️ Aucun changement à commit"
            git push
          else
            echo "✅ index.html déjà présent."
          fi
